-- LaTeX/Unicode symbol library for the FFPL 2026 Rocq course.
--
-- Consumed by aztex.nvim (see lua/lazy/plugins/aztex.lua) via
-- `custom_symbols`. Type the key after a backslash and press Space
-- or Tab to expand it, e.g. \to -> →, \sep -> ∗.
--
-- Add your own entries at the bottom, e.g.  ["mycmd"] = "✗",
--
-- This is a port of the "Iris Math" dictionary from the course's
-- VS Code setup (.devcontainer/devcontainer.json).
--
-- Not triggerable by aztex (keys must match [A-Za-z0-9_^]+):
--   \->  \<->  \<-  \==  \/==  \/=  \<=  \|-  \-  \"o  \^^+  \__+  \^^-
-- Word aliases: -> = to, <- = leftarrow, <-> = iff, <= = leq,
--   /= = ne/neq, == = equiv, - = setminus.

return {
  ["forall"] = "∀",
  ["exists"] = "∃",
  ["lam"] = "λ",
  ["not"] = "¬",
  ["neq"] = "≠",
  ["ne"] = "≠",
  ["nequiv"] = "≢",
  ["leq"] = "≤",
  ["in"] = "∈",
  ["notin"] = "∉",
  ["cup"] = "∪",
  ["cap"] = "∩",
  ["setminus"] = "∖",
  ["subset"] = "⊂",
  ["subseteq"] = "⊆",
  ["sqsubseteq"] = "⊑",
  ["notsubseteq"] = "⊈",
  ["meet"] = "⊓",
  ["join"] = "⊔",
  ["top"] = "⊤",
  ["bottom"] = "⊥",
  ["vdash"] = "⊢",
  ["dashv"] = "⊣",
  ["Vdash"] = "⊨",
  ["infty"] = "∞",
  ["comp"] = "∘",
  ["prf"] = "↾",
  ["bind"] = "≫=",
  ["mapsto"] = "↦",
  ["hookrightarrow"] = "↪",
  ["uparrow"] = "↑",
  ["Uparrow"] = "⇑",
  ["succ"] = "≻",
  ["squigright"] = "⇝",
  ["downarrow"] = "↓",
  ["leftarrow"] = "←",
  ["fun"] = "λ",
  ["mult"] = "⋅",
  ["ent"] = "⊢",
  ["valid"] = "✓",
  ["diamond"] = "◇",
  ["box"] = "□",
  ["bbox"] = "■",
  ["later"] = "▷",
  ["pred"] = "φ",
  ["and"] = "∧",
  ["or"] = "∨",
  ["ccomp"] = "◎",
  ["all"] = "∀",
  ["ex"] = "∃",
  ["to"] = "→",
  ["sep"] = "∗",
  ["star"] = "∗",
  ["lc"] = "⌜",
  ["rc"] = "⌝",
  ["Lc"] = "⎡",
  ["Rc"] = "⎤",
  ["empty"] = "∅",
  ["Lam"] = "Λ",
  ["Sig"] = "Σ",
  ["aa"] = "●",
  ["af"] = "◯",
  ["auth"] = "●",
  ["frag"] = "◯",
  ["iff"] = "↔",
  ["gname"] = "γ",
  ["incl"] = "≼",
  ["latert"] = "▶",
  ["update"] = "⇝",
  ["__0"] = "₀",
  ["__1"] = "₁",
  ["__2"] = "₂",
  ["__3"] = "₃",
  ["__4"] = "₄",
  ["__5"] = "₅",
  ["__6"] = "₆",
  ["__7"] = "₇",
  ["__8"] = "₈",
  ["__9"] = "₉",
  ["__a"] = "ₐ",
  ["__e"] = "ₑ",
  ["__h"] = "ₕ",
  ["__i"] = "ᵢ",
  ["__k"] = "ₖ",
  ["__l"] = "ₗ",
  ["__m"] = "ₘ",
  ["__n"] = "ₙ",
  ["__o"] = "ₒ",
  ["__p"] = "ₚ",
  ["__r"] = "ᵣ",
  ["__s"] = "ₛ",
  ["__t"] = "ₜ",
  ["__u"] = "ᵤ",
  ["__v"] = "ᵥ",
  ["__x"] = "ₓ",
  ["Alpha"] = "Α",
  ["alpha"] = "α",
  ["Beta"] = "Β",
  ["beta"] = "β",
  ["Gamma"] = "Γ",
  ["gamma"] = "γ",
  ["Delta"] = "Δ",
  ["delta"] = "δ",
  ["Epsilon"] = "Ε",
  ["epsilon"] = "ε",
  ["Zeta"] = "Ζ",
  ["zeta"] = "ζ",
  ["Eta"] = "Η",
  ["eta"] = "η",
  ["Theta"] = "Θ",
  ["theta"] = "θ",
  ["Iota"] = "Ι",
  ["iota"] = "ι",
  ["Kappa"] = "Κ",
  ["kappa"] = "κ",
  ["Lamda"] = "Λ",
  ["lamda"] = "λ",
  ["Lambda"] = "Λ",
  ["lambda"] = "λ",
  ["Mu"] = "Μ",
  ["mu"] = "μ",
  ["Nu"] = "Ν",
  ["nu"] = "ν",
  ["Xi"] = "Ξ",
  ["xi"] = "ξ",
  ["Omicron"] = "Ο",
  ["omicron"] = "ο",
  ["Pi"] = "Π",
  ["pi"] = "π",
  ["Rho"] = "Ρ",
  ["rho"] = "ρ",
  ["Sigma"] = "Σ",
  ["sigma"] = "σ",
  ["Tau"] = "Τ",
  ["tau"] = "τ",
  ["Upsilon"] = "Υ",
  ["upsilon"] = "υ",
  ["Phi"] = "Φ",
  ["phi"] = "φ",
  ["Chi"] = "Χ",
  ["chi"] = "χ",
  ["Psi"] = "Ψ",
  ["psi"] = "ψ",
  ["Omega"] = "Ω",
  ["omega"] = "ω",
}
