local function toggle_macro_recording()
  if vim.fn.reg_recording() == '' then
    return 'qq'
  else
    return 'q'
  end
end

local function oil_toggle()
  if vim.bo.filetype == "oil" then
    require("oil").close()
  elseif vim.bo.buftype == "terminal" then
    vim.cmd('e .')
  else
    require("oil").open()
  end
end


vim.api.nvim_set_keymap("n", "<C-CR>", ":term ./r.sh<CR>", { noremap = true })
vim.keymap.set('n', '<leader>e', ":ParseErrors<CR>", { noremap = true, silent = true })
vim.keymap.set('i', '<leader>e', ":ParseErrors<CR>", { noremap = true, silent = true })
vim.keymap.set('v', '<leader>e', ":ParseErrors<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-a>", "ggVG", { noremap = true })
vim.api.nvim_set_keymap("v", "<C-c>", '"+y', { noremap = true })
vim.api.nvim_set_keymap("i", "<C-v>", '<Esc>"+p', { noremap = true })
vim.api.nvim_set_keymap("n", "<C-v>", '"+p', { noremap = true })
vim.api.nvim_set_keymap("v", "<C-v>", '"_d"+P', { noremap = true, silent = true })
vim.keymap.set("n", "<C-N>", oil_toggle, { desc = "Toggle Oil File Explorer" })
vim.api.nvim_set_keymap("n", "<C-s>", ":wa<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("i", "<C-s>", "<Esc>:wa<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("v", "<C-s>", "<Esc>:wa<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("i", "<C-BS>", "<C-W>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-A>", "ggVG", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-Z>", "u", { noremap = true, silent = true })
vim.api.nvim_set_keymap("i", "<C-Z>", "u", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-x>', '"+yy"_dd', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-x>', '<C-o>"+yy<C-o>"_dd', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<C-x>', '"+y<ESC>gv"_d', { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "d", '"_d', { noremap = true })
vim.api.nvim_set_keymap("n", "dd", '"_dd', { noremap = true })
vim.api.nvim_set_keymap("n", "<A-Up>", ":m .-2<CR>==", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<A-Down>", ":m .+1<CR>==", { noremap = true, silent = true })
vim.api.nvim_set_keymap("v", "<A-Up>", ":m '<-2<CR>gv=gv", { noremap = true, silent = true })
vim.api.nvim_set_keymap("v", "<A-Down>", ":m '>+1<CR>gv=gv", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<S-Tab>", "<<", { noremap = true, silent = true })
vim.api.nvim_set_keymap("v", "<S-Tab>", "<gv", { noremap = true, silent = true })
vim.api.nvim_set_keymap("v", "<BS>", '"_d', { noremap = true, silent = true })
vim.api.nvim_set_keymap("v", "<Tab>", ">gv", { noremap = true, silent = true })
vim.api.nvim_set_keymap("t", "<Esc>", "<C-\\><C-n>", { noremap = true, silent = true })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.api.nvim_set_keymap("n", "<S-Home>", "v0", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<S-End>", "v$", { noremap = true, silent = true })
vim.api.nvim_set_keymap("i", "<S-Home>", "<Esc>v0i", { noremap = true, silent = true })
vim.api.nvim_set_keymap("i", "<S-End>", "<Esc>v$i", { noremap = true, silent = true })
vim.keymap.set('v', '<S-right>', 'l', { noremap = true, silent = true })
vim.keymap.set('v', '<S-left>', 'h', { noremap = true, silent = true })
vim.keymap.set('v', '<S-up>', 'k', { noremap = true, silent = true })
vim.keymap.set('v', '<S-down>', 'j', { noremap = true, silent = true })
vim.keymap.set('i', '<S-Up>', '<left><C-o>vk', { noremap = true, silent = true })
vim.keymap.set('i', '<S-Down>', '<C-o>vj', { noremap = true, silent = true })
vim.keymap.set('i', '<S-left>', '<left><C-o>v', { noremap = true, silent = true })
vim.keymap.set('i', '<S-right>', '<C-o>v', { noremap = true, silent = true })
vim.keymap.set('i', '<C-S-left>', '<left><C-o>vb', { noremap = true, silent = true })
vim.keymap.set('i', '<C-S-right>', '<C-o>vw', { noremap = true, silent = true })
vim.keymap.set('i', '<C-Up>', '<C-o><C-y>', { noremap = true, silent = true })
vim.keymap.set('i', '<C-S-Up>', '<C-o><C-v>k', { noremap = true, silent = true })
vim.keymap.set('i', '<C-S-Down>', '<C-o><C-v>j', { noremap = true, silent = true })
vim.keymap.set('n', '<S-Up>', 'vk', { noremap = true, silent = true })
vim.keymap.set('n', '<S-Down>', 'vj', { noremap = true, silent = true })
vim.keymap.set('n', '<S-left>', 'v', { noremap = true, silent = true })
vim.keymap.set('n', '<S-right>', 'v', { noremap = true, silent = true })
vim.keymap.set('n', '<C-S-left>', 'vb', { noremap = true, silent = true })
vim.keymap.set('n', '<C-S-right>', 'vw', { noremap = true, silent = true })
vim.keymap.set('n', '<C-Up>', '<C-y>', { noremap = true, silent = true })
vim.keymap.set('n', '<C-S-Up>', '<C-v>k', { noremap = true, silent = true })
vim.keymap.set('n', '<C-S-Down>', '<C-v>j', { noremap = true, silent = true })
vim.keymap.set('n', 'gf','<C-w>f', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>m', toggle_macro_recording, { noremap = true, silent = true, expr = true })
vim.keymap.set('v', '<leader>m', ":'<,'>norm @q<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-w>>', '20<C-w>>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-w><', '20<C-w><', { noremap = true, silent = true })
vim.keymap.set('n', 'cd', 'ipwd | xclip -selection clipboard<CR><C-\\><C-n>:cd <C-r>+<CR>', { noremap = true, silent = false })
